name: account-zgxw
kind: Deployment
image: ""
container:
  command:
livenessProbe:
  tcpSocket:
    port: 8000
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3
readinessProbe:
  tcpSocket:
    port: 8000
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3
service:
  ports:
    port: 80
    protocol: TCP
    targetPort: 8000

env:
  APPID: 'AK20230314ZGXW'
  APPKEY: '65f51025e8a374984fba505308bcd68c'

