FROM node:14-alpine3.15 as node-build-env
ADD . /tmp/srv
WORKDIR /tmp/srv
RUN set -e && npm config set registry https://registry.npmmirror.com && \
    mkdir -p /data/apps/gosrv && \
    npm run i && \
    npm run build && \
    npm run cp && \
    npm run test && \
    cp -a . /data/apps/gosrv/

FROM arm64v8/node:lts-stretch-slim
ARG grpcAddr
ENV grpcAddr=${grpcAddr}
COPY --from=node-build-env /data/apps/gosrv /data/apps/gosrv
EXPOSE 8000
CMD ["node", "/data/apps/gosrv/dist/src/index.js"]
