syntax = "proto3";

package securityScan;

/* 定义 SecurityScan RPC 服务接口 */
service SecurityScanService {
  rpc scanEngineHeartBeat(ScanEngineHeartBeatRequest) returns (JsonResponse){}
  rpc scanEngineCallBack(ScanEngineCallBackRequest) returns (JsonResponse){}
  rpc getFileDownload(GetFileDownloadRequest) returns (JsonResponse){}
  rpc getFileHistoryDownload(GetFileHistoryDownloadRequest) returns (JsonResponse){}
  rpc getFileHistory(GetFileHistoryRequest) returns (JsonResponse){}
}

message ScanEngineHeartBeatRequest {
    string bodyStr = 1;
}

message ScanEngineCallBackRequest {
    string bodyStr = 1;
}

message GetFileDownloadRequest {
  string groupId = 1;
  string fileId = 2;
  string queryStr = 3;
}

message GetFileHistoryDownloadRequest {
  string historyId = 1;
  string queryStr = 2;
}

message GetFileHistoryRequest {
  string fileId = 1;
  string queryStr = 2;
}

message JsonResponse{
  string result = 1; // ok or error
  string data = 2; // json string
  string msg = 3; // error msg
}
