FROM node:16-alpine3.16 as node-build-env
ADD . /tmp/srv
WORKDIR /tmp/srv
RUN set -e && npm config set registry https://registry.npm.taobao.org && \
    sh build.sh && mkdir -p /data/apps/gosrv && \
    npm run test && \
    cp -a . /data/apps/gosrv/

FROM arm64v8/node:lts-stretch-slim
ARG grpcAddr
ENV grpcAddr=${grpcAddr}
# 设置镜像的时区
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone
COPY --from=node-build-env /data/apps/gosrv /data/apps/gosrv
EXPOSE 8000
CMD ["node", "/data/apps/gosrv/dist/src/index.js"]
