name: account-user
kind: Deployment
image: ""
container:
  command:
livenessProbe:
  tcpSocket:
    port: 8000
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3
readinessProbe:
  tcpSocket:
    port: 8000
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3
service:
  ports:
    port: 80
    protocol: TCP
    targetPort: 8000

env:
  APPID: 'ak20230306zzwj'
  APPKEY: 'WrSmo7Qz1Uqkh44a8gIexDI7Lcnq0PlQ'

